<a href="https://colab.research.google.com/github/PabloC1700/C-digos-TFM---Py-Colab-/blob/main/TP5/Equipos_Fbref.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install LanusStats

Requirement already satisfied: LanusStats in /usr/local/lib/python3.10/dist-packages (1.5.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from LanusStats) (2.0.3)
Requirement already satisfied: mplsoccer in /usr/local/lib/python3.10/dist-packages (from LanusStats) (1.2.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from LanusStats) (2.31.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from LanusStats) (3.7.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from LanusStats) (1.25.2)
Requirement already satisfied: bs4 in /usr/local/lib/python3.10/dist-packages (from LanusStats) (0.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from LanusStats) (9.4.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4->LanusStats) (4.12.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->LanusStats) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->LanusStats) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->LanusStats) (4.52.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->LanusStats) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->LanusStats) (24.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->LanusStats) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->LanusStats) (2.8.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from mplsoccer->LanusStats) (1.11.4)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from mplsoccer->LanusStats) (0.13.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->LanusStats) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->LanusStats) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->LanusStats) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->LanusStats) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->LanusStats) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->LanusStats) (2024.2.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->LanusStats) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4->LanusStats) (2.5)

In [ ]:
import LanusStats as ls

In [ ]:
ls.get_available_pages()

dict_keys(['Fbref', 'Sofascore', '365Scores', 'Fotmob'])

In [ ]:
ls.get_available_leagues('Fbref')

['Copa de la Liga',
 'Primera Division Argentina',
 'Primera Division Uruguay',
 'Brasileirao',
 'Brasileirao B',
 'Primera Division Colombia',
 'Primera Division Chile',
 'Primera Division Peru',
 'Primera Division Venezuela',
 'Primera Division Ecuador',
 'Primera Division Bolivia',
 'Primera Division Paraguay',
 'Brasileirao F',
 'MLS',
 'USL Championship',
 'Premier League',
 'La Liga',
 'Ligue 1',
 'Bundesliga',
 'Serie A',
 'Big 5 European Leagues',
 'Danish Superliga',
 'Eredivise',
 'Primeira Liga Portugal']

In [ ]:
ls.get_available_season_for_leagues('Fbref','Serie A')

{'id': 11,
 'slug': 'Serie-A',
 'seasons': {'2020-2021', '2021-2022', '2022-2023', '2023-2024'}}

In [ ]:
Fbref= ls.Fbref()

In [ ]:
Fbref.get_teams_season_stats('stats','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,...,Gls,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG
0,Atalanta,27,26.5,49.9,38,418,3420,38.0,64,42,...,1.68,1.11,2.79,1.53,2.63,1.52,1.12,2.64,1.35,2.47
1,Bologna,27,26.6,54.7,38,418,3420,38.0,52,41,...,1.37,1.08,2.45,1.21,2.29,1.15,0.83,1.98,1.04,1.87
2,Cremonese,33,26.0,42.1,38,418,3420,38.0,35,18,...,0.92,0.47,1.39,0.79,1.26,1.02,0.64,1.66,0.87,1.51
3,Empoli,32,25.3,47.3,38,418,3420,38.0,35,20,...,0.92,0.53,1.45,0.87,1.39,1.02,0.71,1.73,0.98,1.69
4,Fiorentina,30,26.5,56.1,38,418,3420,38.0,51,37,...,1.34,0.97,2.32,1.24,2.21,1.45,1.06,2.51,1.34,2.39
5,Hellas Verona,36,26.6,41.2,38,418,3420,38.0,29,22,...,0.76,0.58,1.34,0.74,1.32,0.94,0.74,1.68,0.92,1.66
6,Inter,25,28.8,55.7,38,418,3420,38.0,68,50,...,1.79,1.32,3.11,1.68,3.00,1.79,1.36,3.15,1.70,3.06
7,Juventus,29,27.7,49.6,38,418,3420,38.0,56,41,...,1.47,1.08,2.55,1.39,2.47,1.45,1.05,2.50,1.33,2.37
8,Lazio,24,28.6,52.1,38,418,3420,38.0,59,37,...,1.55,0.97,2.53,1.39,2.37,1.35,0.90,2.25,1.18,2.08
9,Lecce,29,24.8,41.3,38,418,3420,38.0,31,21,...,0.82,0.55,1.37,0.71,1.26,0.95,0.66,1.61,0.83,1.49
10,Milan,30,26.0,55.6,38,418,3420,38.0,61,49,...,1.61,1.29,2.89,1.47,2.76,1.55,1.21,2.76,1.45,2.66
11,Monza,31,26.6,55.2,38,418,3420,38.0,46,31,...,1.21,0.82,2.03,1.08,1.89,1.21,0.89,2.10,1.08,1.97
12,Napoli,27,26.4,61.8,38,418,3420,38.0,75,57,...,1.97,1.50,3.47,1.76,3.26,1.70,1.23,2.94,1.50,2.73
13,Roma,30,27.4,48.6,38,418,3420,38.0,50,33,...,1.32,0.87,2.18,1.13,2.00,1.51,1.02,2.53,1.31,2.34
14,Salernitana,30,27.2,44.9,38,418,3420,38.0,46,34,...,1.21,0.89,2.11,1.16,2.05,0.96,0.71,1.67,0.93,1.63
15,Sampdoria,40,27.9,46.1,38,418,3420,38.0,23,18,...,0.61,0.47,1.08,0.58,1.05,0.90,0.64,1.54,0.85,1.50
16,Sassuolo,31,26.1,49.2,38,418,3420,38.0,46,30,...,1.21,0.79,2.00,0.97,1.76,1.36,0.95,2.31,1.16,2.11
17,Spezia,34,25.7,47.4,38,418,3420,38.0,29,18,...,0.76,0.47,1.24,0.66,1.13,1.09,0.77,1.86,1.01,1.78
18,Torino,28,25.2,53.2,38,418,3420,38.0,41,34,...,1.08,0.89,1.97,1.03,1.92,1.10,0.92,2.02,1.06,1.98
19,Udinese,30,26.1,48.0,38,418,3420,38.0,46,41,...,1.21,1.08,2.29,1.18,2.26,1.24,0.99,2.23,1.20,2.19

In [ ]:
Fbref.get_teams_season_stats('shooting','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,90s,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,Atalanta,27,38.0,64,506,168,33.2,13.32,4.42,0.11,0.35,16.9,13,6,8,57.7,51.3,0.10,6.3,6.7
1,Bologna,27,38.0,52,479,150,31.3,12.61,3.95,0.10,0.31,19.6,18,6,6,43.8,39.4,0.08,8.2,6.6
2,Cremonese,33,38.0,35,458,122,26.6,12.05,3.21,0.07,0.25,18.5,15,5,7,38.7,33.2,0.07,-3.7,-3.2
3,Empoli,32,38.0,35,447,129,28.9,11.76,3.39,0.07,0.26,18.3,19,2,2,38.8,37.2,0.09,-3.8,-4.2
4,Fiorentina,30,38.0,51,597,171,28.6,15.71,4.50,0.08,0.27,17.6,23,4,6,55.0,50.8,0.09,-4.0,-3.8
5,Hellas Verona,36,38.0,29,415,116,28.0,10.92,3.05,0.07,0.24,18.6,13,1,1,35.8,35.1,0.09,-6.8,-7.1
6,Inter,25,38.0,68,625,197,31.5,16.45,5.18,0.10,0.32,16.9,21,4,5,68.0,64.5,0.11,0.0,-0.5
7,Juventus,29,38.0,56,529,171,32.3,13.92,4.50,0.10,0.31,17.3,19,3,6,55.3,50.4,0.10,0.7,2.6
8,Lazio,24,38.0,59,430,161,37.4,11.32,4.24,0.12,0.33,17.8,14,6,8,51.1,44.9,0.11,7.9,8.1
9,Lecce,29,38.0,31,412,106,25.7,10.84,2.79,0.07,0.25,18.8,14,4,6,36.1,31.4,0.08,-5.1,-4.4
10,Milan,30,38.0,61,546,178,32.6,14.37,4.68,0.10,0.31,17.7,26,5,5,58.8,55.1,0.10,2.2,0.9
11,Monza,31,38.0,46,406,139,34.2,10.68,3.66,0.10,0.29,17.9,13,5,6,45.9,41.2,0.10,0.1,-0.2
12,Napoli,27,38.0,75,605,212,35.0,15.92,5.58,0.11,0.32,17.1,18,8,10,64.7,56.8,0.10,10.3,10.2
13,Roma,30,38.0,50,488,155,31.8,12.84,4.08,0.09,0.28,17.0,15,7,10,57.4,49.9,0.10,-7.4,-6.9
14,Salernitana,30,38.0,46,381,115,30.2,10.03,3.03,0.12,0.38,18.9,14,2,2,36.7,35.2,0.09,9.3,8.8
15,Sampdoria,40,38.0,23,376,114,30.3,9.89,3.00,0.06,0.19,17.8,16,1,2,34.1,32.5,0.09,-11.1,-10.5
16,Sassuolo,31,38.0,46,477,161,33.8,12.55,4.24,0.08,0.23,18.0,20,9,10,51.6,43.9,0.09,-5.6,-6.9
17,Spezia,34,38.0,29,419,120,28.6,11.03,3.16,0.06,0.21,18.3,19,4,4,41.5,38.5,0.09,-12.5,-13.5
18,Torino,28,38.0,41,444,146,32.9,11.68,3.84,0.09,0.27,16.7,6,2,2,41.8,40.2,0.09,-0.8,-1.2
19,Udinese,30,38.0,46,503,145,28.8,13.24,3.82,0.09,0.31,18.5,23,1,2,46.9,45.4,0.09,-0.9,-0.4

In [ ]:
Fbref.get_teams_season_stats('passing','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,90s,Cmp,Att,Cmp%,TotDist,PrgDist,Cmp,Att,...,Cmp%,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP
0,Atalanta,27,38.0,15462,19507,79.3,267971,97492,7245,8234,...,54.9,42,42.7,40.8,-0.7,405,1184,385,89,1637
1,Bologna,27,38.0,16763,20552,81.6,290293,103110,7901,8808,...,58.3,41,31.5,26.0,9.5,371,1120,246,67,1366
2,Cremonese,33,38.0,10872,15041,72.3,200114,82419,4733,5616,...,44.4,18,24.3,21.9,-6.3,325,936,275,107,1107
3,Empoli,32,38.0,13199,16862,78.3,234132,88608,5889,6670,...,52.3,20,26.8,24.1,-6.8,322,776,245,76,1114
4,Fiorentina,30,38.0,15373,19236,79.9,294347,99945,6120,6942,...,60.6,37,40.2,36.7,-3.2,462,1219,353,121,1627
5,Hellas Verona,36,38.0,9481,13807,68.7,186844,85475,3784,4825,...,48.5,22,28.1,23.0,-6.1,304,861,232,88,1063
6,Inter,25,38.0,17693,21281,83.1,320024,109417,7531,8348,...,61.1,50,51.8,46.8,-1.8,479,1272,390,134,1624
7,Juventus,29,38.0,15226,18690,81.5,285025,99282,6319,7141,...,61.9,41,39.8,29.8,1.2,404,1163,295,90,1394
8,Lazio,24,38.0,18135,21629,83.8,293491,106673,9434,10386,...,62.4,37,34.3,30.0,2.7,325,1214,283,44,1381
9,Lecce,29,38.0,10083,14358,70.2,188701,76019,4285,5217,...,44.8,21,25.3,20.6,-4.3,313,965,218,79,1232
10,Milan,30,38.0,15948,19734,80.8,289152,100822,6781,7765,...,60.1,49,46.0,39.2,3.0,416,1165,359,88,1584
11,Monza,31,38.0,17198,20724,83.0,308969,105210,7443,8250,...,61.3,31,33.8,28.7,-2.8,312,1154,278,71,1362
12,Napoli,27,38.0,21086,24473,86.2,349837,113047,10412,11275,...,66.9,57,46.8,42.9,10.2,490,1638,411,89,1804
13,Roma,30,38.0,14171,17814,79.5,257681,88761,6089,6899,...,56.9,33,38.9,33.4,-5.9,368,960,261,56,1217
14,Salernitana,30,38.0,12667,16508,76.7,223947,85787,5739,6539,...,48.7,34,26.9,20.8,7.1,280,845,209,70,1089
15,Sampdoria,40,38.0,12606,16575,76.1,231539,88820,5369,6223,...,52.6,18,24.4,25.1,-6.4,272,886,241,74,1126
16,Sassuolo,31,38.0,14805,18306,80.9,269825,99100,6480,7323,...,61.6,30,36.1,31.5,-6.1,371,1092,328,82,1565
17,Spezia,34,38.0,12399,16501,75.1,215537,84262,5772,6701,...,45.8,18,29.3,26.8,-11.3,289,928,267,84,1163
18,Torino,28,38.0,15376,19336,79.5,275969,93628,6788,7659,...,50.9,34,35.0,30.1,-1.0,375,1159,274,89,1328
19,Udinese,30,38.0,13391,16790,79.8,246847,93352,5689,6485,...,59.0,41,37.8,33.3,3.2,384,1009,295,70,1354

In [ ]:
Fbref.get_teams_season_stats('passing_types','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,90s,Att,Live,Dead,FK,TB,Sw,Crs,TI,CK,In,Out,Str,Cmp,Off,Blocks
0,Atalanta,27,38.0,19507,17537,1912,432,35,154,652,893,194,97,67,0,15462,58,359
1,Bologna,27,38.0,20552,18623,1852,484,58,179,558,830,145,90,41,0,16763,77,368
2,Cremonese,33,38.0,15041,13147,1826,482,26,99,659,768,146,51,76,0,10872,68,300
3,Empoli,32,38.0,16862,14830,1978,538,24,105,611,828,163,70,61,0,13199,54,375
4,Fiorentina,30,38.0,19236,17189,1991,600,30,203,880,831,234,88,99,0,15373,56,336
5,Hellas Verona,36,38.0,13807,12006,1727,437,23,81,652,721,170,81,63,1,9481,74,334
6,Inter,25,38.0,21281,19504,1709,443,50,185,885,682,214,66,121,0,17693,68,275
7,Juventus,29,38.0,18690,16884,1744,449,38,195,731,706,207,64,125,1,15226,62,318
8,Lazio,24,38.0,21629,19809,1766,540,55,135,483,680,169,71,76,0,18135,54,330
9,Lecce,29,38.0,14358,12384,1906,504,23,175,709,858,172,56,61,0,10083,68,315
10,Milan,30,38.0,19734,17874,1799,472,52,126,671,813,187,51,108,0,15948,61,322
11,Monza,31,38.0,20724,18818,1837,570,33,168,596,711,154,22,111,0,17198,69,327
12,Napoli,27,38.0,24473,22587,1826,515,36,200,681,785,228,84,74,1,21086,60,337
13,Roma,30,38.0,17814,15874,1884,528,59,176,595,833,188,84,93,0,14171,56,292
14,Salernitana,30,38.0,16508,14589,1852,530,25,140,559,720,143,23,66,0,12667,67,324
15,Sampdoria,40,38.0,16575,14576,1944,598,34,107,599,760,130,36,77,0,12606,55,380
16,Sassuolo,31,38.0,18306,16248,2015,566,34,195,625,798,177,81,50,0,14805,43,351
17,Spezia,34,38.0,16501,14437,2009,456,26,107,655,922,193,116,53,0,12399,55,381
18,Torino,28,38.0,19336,17523,1733,445,36,117,610,742,172,99,42,1,15376,80,336
19,Udinese,30,38.0,16790,14908,1831,536,37,213,564,707,186,76,52,0,13391,51,329

In [ ]:
Fbref.get_teams_season_stats('gca','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,90s,SCA,SCA90,PassLive,PassDead,TO,Sh,Fld,Def,GCA,GCA90,PassLive,PassDead,TO,Sh,Fld,Def
0,Atalanta,27,38.0,928,24.42,681,87,64,51,33,12,113,2.97,83,5,6,11,7,1
1,Bologna,27,38.0,866,22.79,642,72,45,49,46,12,91,2.39,64,11,3,7,6,0
2,Cremonese,33,38.0,789,20.76,551,81,37,61,45,14,53,1.39,31,5,4,9,4,0
3,Empoli,32,38.0,767,20.18,537,77,46,46,47,14,60,1.58,39,6,6,5,4,0
4,Fiorentina,30,38.0,1068,28.11,763,113,54,70,53,15,89,2.34,64,6,7,7,4,1
5,Hellas Verona,36,38.0,704,18.53,482,90,41,42,29,20,50,1.32,31,4,5,7,2,1
6,Inter,25,38.0,1104,29.05,816,117,29,79,52,11,118,3.11,88,4,7,10,7,2
7,Juventus,29,38.0,911,23.97,638,94,50,77,38,14,91,2.39,61,7,3,9,9,2
8,Lazio,24,38.0,760,20.00,576,56,44,43,32,9,103,2.71,78,3,6,11,5,0
9,Lecce,29,38.0,699,18.39,483,84,43,42,38,9,50,1.32,38,2,4,3,2,1
10,Milan,30,38.0,985,25.92,688,91,65,68,58,15,111,2.92,76,6,15,7,4,3
11,Monza,31,38.0,714,18.79,537,60,30,40,35,12,86,2.26,62,5,6,4,8,1
12,Napoli,27,38.0,1105,29.08,819,92,58,66,47,23,131,3.45,98,8,4,14,6,1
13,Roma,30,38.0,861,22.66,574,110,43,68,53,13,85,2.24,52,10,5,12,5,1
14,Salernitana,30,38.0,656,17.26,489,58,27,44,30,8,81,2.13,64,4,4,7,2,0
15,Sampdoria,40,38.0,637,16.76,456,52,28,46,39,16,36,0.95,26,2,1,4,1,2
16,Sassuolo,31,38.0,871,22.92,684,50,49,41,34,13,81,2.13,56,4,4,10,7,0
17,Spezia,34,38.0,710,18.68,511,61,39,43,38,18,42,1.11,29,1,3,5,4,0
18,Torino,28,38.0,821,21.61,635,61,52,40,21,12,74,1.95,58,2,7,4,3,0
19,Udinese,30,38.0,889,23.39,625,87,53,58,51,15,80,2.11,61,6,3,3,5,2

In [ ]:
Fbref.get_teams_season_stats('defense','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,90s,Tkl,TklW,Def 3rd,Mid 3rd,Att 3rd,Tkl,Att,Tkl%,Lost,Blocks,Sh,Pass,Int,Tkl+Int,Clr,Err
0,Atalanta,27,38.0,636,364,291,272,73,312,634,49.2,322,455,93,362,421,1057,613,12
1,Bologna,27,38.0,648,373,310,255,83,297,618,48.1,321,414,131,283,302,950,652,7
2,Cremonese,33,38.0,704,400,403,228,73,364,729,49.9,365,432,136,296,393,1097,771,13
3,Empoli,32,38.0,606,364,316,218,72,254,538,47.2,284,449,183,266,280,886,910,4
4,Fiorentina,30,38.0,581,337,232,260,89,282,531,53.1,249,356,84,272,260,841,473,11
5,Hellas Verona,36,38.0,605,357,319,228,58,296,562,52.7,266,445,143,302,337,942,745,12
6,Inter,25,38.0,572,325,247,241,84,258,523,49.3,265,385,110,275,315,887,541,7
7,Juventus,29,38.0,594,352,296,219,79,288,558,51.6,270,421,131,290,307,901,704,10
8,Lazio,24,38.0,582,349,261,234,87,277,625,44.3,348,437,126,311,310,892,606,8
9,Lecce,29,38.0,705,427,347,259,99,319,619,51.5,300,486,112,374,368,1073,826,4
10,Milan,30,38.0,690,422,327,295,68,300,563,53.3,263,387,126,261,289,979,542,9
11,Monza,31,38.0,595,355,323,214,58,260,551,47.2,291,380,120,260,334,929,661,13
12,Napoli,27,38.0,569,313,236,227,106,255,521,48.9,266,374,96,278,287,856,490,7
13,Roma,30,38.0,624,340,301,257,66,289,617,46.8,328,392,113,279,368,992,590,9
14,Salernitana,30,38.0,587,337,309,220,58,259,569,45.5,310,409,157,252,329,916,740,13
15,Sampdoria,40,38.0,589,351,290,240,59,261,558,46.8,297,428,152,276,317,906,688,7
16,Sassuolo,31,38.0,502,281,237,186,79,216,461,46.9,245,371,122,249,278,780,658,16
17,Spezia,34,38.0,622,359,290,236,96,254,569,44.6,315,457,161,296,301,923,830,7
18,Torino,28,38.0,473,265,231,187,55,199,367,54.2,168,337,110,227,292,765,627,9
19,Udinese,30,38.0,651,365,363,228,60,326,632,51.6,306,437,128,309,314,965,712,8

In [ ]:
Fbref.get_teams_season_stats('possession','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,Poss,90s,Touches,Def Pen,Def 3rd,Mid 3rd,Att 3rd,Att Pen,...,Carries,TotDist,PrgDist,PrgC,1/3,CPA,Mis,Dis,Rec,PrgR
0,Atalanta,27,49.9,38.0,23862,2217,7478,10221,6382,956,...,13148,67208,33188,687,565,210,619,387,15359,1628
1,Bologna,27,54.7,38.0,24552,2551,8483,11383,4893,592,...,14223,70806,35047,564,487,113,582,305,16622,1358
2,Cremonese,33,42.1,38.0,19346,2538,7184,8051,4334,678,...,9843,51780,26321,521,394,101,553,297,10770,1100
3,Empoli,32,47.3,38.0,21188,2962,8175,8766,4485,674,...,11736,64438,31714,608,452,135,552,372,13050,1105
4,Fiorentina,30,56.1,38.0,23123,2028,6652,10361,6366,977,...,13434,77635,39528,789,601,194,572,345,15234,1607
5,Hellas Verona,36,41.2,38.0,18056,2231,6320,7844,4147,636,...,8665,47590,22382,503,359,103,577,329,9350,1051
6,Inter,25,55.7,38.0,25128,2720,8300,11127,5922,953,...,14972,75152,38723,668,492,141,505,261,17526,1613
7,Juventus,29,49.6,38.0,22810,2432,7514,10435,5077,817,...,12888,66636,34490,673,496,145,583,350,15118,1389
8,Lazio,24,52.1,38.0,25453,2536,8100,12315,5243,769,...,14379,73160,36610,683,484,182,528,290,18009,1368
9,Lecce,29,41.3,38.0,18839,2129,6291,8105,4660,606,...,9288,51809,25326,515,366,119,626,329,9976,1219
10,Milan,30,55.6,38.0,23856,2177,7373,11143,5617,891,...,13802,78895,41728,795,584,182,595,320,15792,1576
11,Monza,31,55.2,38.0,24603,2753,8855,11185,4768,680,...,14329,79216,38961,708,500,152,575,309,17052,1350
12,Napoli,27,61.8,38.0,28410,2012,7168,13935,7548,1084,...,17977,89551,46645,907,663,237,566,339,20948,1789
13,Roma,30,48.6,38.0,21861,2055,7183,10374,4566,789,...,12407,68172,34789,684,490,170,559,318,14018,1198
14,Salernitana,30,44.9,38.0,20527,2604,7592,9096,4060,495,...,11169,57765,27404,519,409,86,564,303,12529,1076
15,Sampdoria,40,46.1,38.0,20460,2511,7278,9134,4272,585,...,11329,55044,26171,466,354,82,572,335,12492,1118
16,Sassuolo,31,49.2,38.0,22100,2484,7486,9584,5249,817,...,13042,71240,36974,761,527,204,533,364,14664,1552
17,Spezia,34,47.4,38.0,20952,2701,7867,8357,4959,692,...,10996,60775,29636,553,397,114,659,366,12304,1156
18,Torino,28,53.2,38.0,23243,2286,7273,10798,5380,733,...,13094,71281,34612,684,527,182,618,314,15247,1317
19,Udinese,30,48.0,38.0,21183,2463,7415,9101,4912,849,...,12105,65755,33221,646,461,163,641,336,13268,1344

In [ ]:
Fbref.get_teams_season_stats('playingtime','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,Age,MP,Min,Mn/MP,Min%,90s,Starts,Mn/Start,...,unSub,PPM,onG,onGA,+/-,+/-90,onxG,onxGA,xG+/-,xG+/-90
0,Atalanta,27,26.5,38,3420,90,100,38.0,418,80,...,212,1.68,66,48,18,0.47,57.7,41.4,16.3,0.43
1,Bologna,27,26.6,38,3420,90,100,38.0,418,81,...,261,1.42,53,49,4,0.11,43.8,48.7,-4.9,-0.13
2,Cremonese,33,26.0,38,3420,90,100,38.0,418,79,...,302,0.71,36,69,-33,-0.87,38.7,66.1,-27.4,-0.72
3,Empoli,32,25.3,38,3420,90,100,38.0,418,80,...,331,1.13,37,49,-12,-0.32,38.8,58.3,-19.5,-0.51
4,Fiorentina,30,26.5,38,3420,90,100,38.0,418,79,...,323,1.47,53,43,10,0.26,55.0,43.4,11.7,0.31
5,Hellas Verona,36,26.6,38,3420,90,100,38.0,418,79,...,307,0.82,31,59,-28,-0.74,35.8,49.9,-14.1,-0.37
6,Inter,25,28.8,38,3420,90,100,38.0,418,81,...,271,1.89,71,42,29,0.76,68.0,36.5,31.6,0.83
7,Juventus,29,27.7,38,3420,90,100,38.0,418,81,...,240,1.89,56,33,23,0.61,55.3,41.6,13.7,0.36
8,Lazio,24,28.6,38,3420,90,100,38.0,418,82,...,328,1.95,60,30,30,0.79,51.1,41.3,9.8,0.26
9,Lecce,29,24.8,38,3420,90,100,38.0,418,81,...,347,0.95,33,46,-13,-0.34,36.1,42.1,-6.1,-0.16
10,Milan,30,26.0,38,3420,90,100,38.0,418,80,...,321,1.84,64,43,21,0.55,58.8,41.1,17.7,0.47
11,Monza,31,26.6,38,3420,90,100,38.0,418,79,...,363,1.37,48,52,-4,-0.11,45.9,51.3,-5.4,-0.14
12,Napoli,27,26.4,38,3420,90,100,38.0,418,82,...,319,2.37,77,28,49,1.29,64.7,31.8,33.0,0.87
13,Roma,30,27.4,38,3420,90,100,38.0,418,81,...,307,1.66,50,38,12,0.32,57.4,32.1,25.3,0.67
14,Salernitana,30,27.2,38,3420,90,100,38.0,418,80,...,296,1.11,48,62,-14,-0.37,36.7,67.1,-30.5,-0.80
15,Sampdoria,40,27.9,38,3420,90,100,38.0,418,80,...,252,0.50,24,71,-47,-1.24,34.1,66.3,-32.2,-0.85
16,Sassuolo,31,26.1,38,3420,90,100,38.0,418,81,...,291,1.18,47,61,-14,-0.37,51.6,49.7,1.9,0.05
17,Spezia,34,25.7,38,3420,90,100,38.0,418,81,...,310,0.82,31,62,-31,-0.82,41.5,59.5,-18.0,-0.47
18,Torino,28,25.2,38,3420,90,100,38.0,418,82,...,304,1.39,42,41,1,0.03,41.8,40.0,1.8,0.05
19,Udinese,30,26.1,38,3420,90,100,38.0,418,82,...,259,1.21,47,48,-1,-0.03,46.9,51.8,-4.9,-0.13

In [ ]:
Fbref.get_teams_season_stats('misc','Serie A','2022-2023')

Starting to scrape teams data from Fbref...

,Squad,# Pl,90s,CrdY,CrdR,2CrdY,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG,Recov,Won,Lost,Won%
0,Atalanta,27,38.0,83,3,1,470,385,58,652,421,364,6,3,2,2234,575,483,54.3
1,Bologna,27,38.0,84,3,2,477,426,77,558,302,373,5,9,3,2080,369,447,45.2
2,Cremonese,33,38.0,81,3,0,458,407,68,659,393,400,5,5,1,2059,562,730,43.5
3,Empoli,32,38.0,88,7,3,441,459,54,611,280,364,2,6,1,1815,434,519,45.5
4,Fiorentina,30,38.0,93,3,2,488,511,56,880,260,337,3,8,2,2016,588,517,53.2
5,Hellas Verona,36,38.0,103,3,0,540,383,74,652,337,357,1,2,3,2238,810,735,52.4
6,Inter,25,38.0,65,3,2,444,406,68,885,315,325,4,3,3,1948,500,415,54.6
7,Juventus,29,38.0,74,6,1,456,409,62,731,307,352,6,5,0,1951,486,477,50.5
8,Lazio,24,38.0,87,2,0,400,471,54,483,310,349,6,2,1,1979,399,381,51.2
9,Lecce,29,38.0,86,2,1,553,439,68,709,368,427,4,6,3,2120,567,728,43.8
10,Milan,30,38.0,90,2,2,449,438,61,671,289,422,3,5,1,2051,561,478,54.0
11,Monza,31,38.0,90,4,1,489,495,69,596,334,355,6,3,1,1845,448,441,50.4
12,Napoli,27,38.0,47,1,0,389,468,60,681,287,313,8,2,0,2027,483,403,54.5
13,Roma,30,38.0,83,4,2,446,505,56,595,368,340,6,3,1,1981,543,429,55.9
14,Salernitana,30,38.0,85,4,1,473,439,67,559,329,337,1,11,0,1981,528,585,47.4
15,Sampdoria,40,38.0,108,3,2,507,512,55,599,317,351,1,11,2,1913,617,636,49.2
16,Sassuolo,31,38.0,90,6,3,408,443,43,625,278,281,6,4,2,1756,375,438,46.1
17,Spezia,34,38.0,103,6,4,519,379,55,655,301,359,2,7,3,2033,535,570,48.4
18,Torino,28,38.0,81,0,0,506,382,80,610,292,265,2,6,0,2010,590,629,48.4
19,Udinese,30,38.0,88,3,1,478,476,51,564,314,365,1,7,2,1916,477,406,54.0

In [ ]:
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [ ]:
import pandas as pd
import os

# Lista de nombres de tablas
table_names = ['stats', 'keepers', 'keepersadv', 'shooting','passing','passing_types', 'gca', 'defense', 'possession', 'playingtime', 'misc']

# Diccionario para almacenar los DataFrames
dataframes = {}

# Suponiendo que usas fbref.get_player_season_stats para obtener los DataFrames
# Cargar las tablas en el diccionario
for table_name in table_names:
    dataframes[table_name] = Fbref.get_teams_season_stats(table_name, 'Serie A', '2023-2024')

# Definir el nombre del archivo Excel
file_path = 'Serie A_2324 - FBREF Equipos.xlsx'

# Escribir los DataFrames a un archivo Excel con diferentes hojas
with pd.ExcelWriter(file_path, engine='openpyxl') as writer:
    for sheet_name, dataframe in dataframes.items():
        dataframe.to_excel(writer, sheet_name=sheet_name, index=False)

print("Archivo Excel guardado con éxito.")

Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Starting to scrape teams data from Fbref...
Archivo Excel guardado con éxito.